#!/usr/bin/env ruby

require "sheap"
require "irb"

usage = <<~USAGE
Usage: sheap                       # Start an IRB session with Sheap loaded
       sheap HEAPDUMP              # Load a heap dump within an IRB session
       sheap BEFORE AFTER [LATER]  # Compare heap dumps within an IRB session
USAGE

if ARGV.size == 0
elsif ARGV.size == 1 && ARGV[0] == "--help"
  $stderr.puts usage
  exit
elsif ARGV.size == 1
  $heap = @heap = Sheap::Heap.new(ARGV.shift)
  puts("$heap: #{@heap.inspect}")
elsif ARGV.size == 2
  $before = @before = Sheap::Heap.new(ARGV.shift)
  $after = @after = Sheap::Heap.new(ARGV.shift)
  $diff = @diff = Sheap::Diff.new(@before, @after)
  puts("$before: #{@before.inspect}, $after: #{@after.inspect}, $diff: #{@diff.inspect}")
elsif ARGV.size == 3
  $before = @before = Sheap::Heap.new(ARGV.shift)
  $after = @after = Sheap::Heap.new(ARGV.shift)
  $later = @later = Sheap::Heap.new(ARGV.shift)
  $diff = @diff = Sheap::Diff.new(@before, @after, @later)
  puts("$before: #{@before.inspect}, $after: #{@after.inspect}, $later: #{@later.inspect}, $diff: #{@diff.inspect}")
else
  $stderr.puts usage
  exit
end

require 'irb'
IRB.setup nil
IRB.conf[:MAIN_CONTEXT] = IRB::Irb.new.context
require 'irb/ext/multi-irb'
IRB.irb nil, @heap
